<?php
namespace App\Service;
use App\Entity\{Aluno,Assinatura,NotificacaoLog,PagamentoSaas,Plano,ProjetoSocial,Turma,User};
use Doctrine\ORM\EntityManagerInterface;
final class BillingManager {
 public function __construct(private EntityManagerInterface $em){}
 public function subscription(ProjetoSocial $project):?Assinatura{return $this->em->getRepository(Assinatura::class)->findOneBy(['projeto'=>$project]);}
 public function defaultTrialPlan():Plano{$plan=$this->em->getRepository(Plano::class)->findOneBy(['publico'=>true,'ativo'=>true],['valorMensal'=>'ASC']);if($plan)return $plan;$plan=new Plano();$plan->nome='Teste';$plan->valorMensal='0.00';$plan->limiteUsuarios=5;$plan->limiteTurmas=3;$plan->limiteAlunos=50;$plan->limiteNotificacoesMes=100;$plan->diasTeste=14;$plan->recursos=['gestao_alunos','gestao_turmas','gestao_aulas','frequencia','relatorios'];$plan->canaisNotificacao=['email'];$this->em->persist($plan);return $plan;}
 public function createTrial(ProjetoSocial $project,?Plano $plan=null):Assinatura{$plan??=$this->defaultTrialPlan();$subscription=new Assinatura();$subscription->projeto=$project;$subscription->plano=$plan;$subscription->status=$plan->diasTeste>0?'teste':'ativa';$period=$plan->diasTeste>0?$plan->diasTeste:30;$subscription->vencimento=new \DateTimeImmutable('+'.$period.' days');$this->em->persist($subscription);return $subscription;}
 public function hasFeature(ProjetoSocial $project,string $feature):bool{$subscription=$this->subscription($project);if(!$subscription||!$subscription->acessoLiberado())return false;return in_array('todos',$subscription->plano->recursos,true)||in_array($feature,$subscription->plano->recursos,true);}
 public function canCreate(ProjetoSocial $project,string $resource):bool{$subscription=$this->subscription($project);if(!$subscription||!$subscription->acessoLiberado())return false;return match($resource){'usuarios'=>$this->em->getRepository(User::class)->count(['projeto'=>$project])<$subscription->limiteUsuarios(),'turmas'=>$this->em->getRepository(Turma::class)->count(['projeto'=>$project])<$subscription->plano->limiteTurmas,'alunos'=>$subscription->plano->limiteAlunos===null||$this->em->getRepository(Aluno::class)->count(['projeto'=>$project])<$subscription->plano->limiteAlunos,default=>true};}
 public function canAddUser(ProjetoSocial $project):bool{return $this->canCreate($project,'usuarios');}
 public function canNotify(ProjetoSocial $project,string $channel):bool{$subscription=$this->subscription($project);if(!$subscription||!$this->hasFeature($project,'notificacoes')||!in_array($channel,$subscription->plano->canaisNotificacao,true))return false;$limit=$subscription->plano->limiteNotificacoesMes;if($limit===null)return true;$from=new \DateTimeImmutable('first day of this month 00:00:00');$count=$this->em->getRepository(NotificacaoLog::class)->createQueryBuilder('n')->select('COUNT(n.id)')->where('n.projeto = :p')->andWhere('n.criadoEm >= :from')->setParameter('p',$project)->setParameter('from',$from)->getQuery()->getSingleScalarResult();return (int)$count<$limit;}
 public function markPaid(PagamentoSaas $payment):void{$payment->status='pago';$payment->pagoEm=new \DateTimeImmutable();$subscription=$payment->assinatura;$subscription->status='ativa';$base=$subscription->vencimento>new \DateTimeImmutable('today')?$subscription->vencimento:new \DateTimeImmutable('today');$subscription->vencimento=$base->modify('+1 month');}
}
