<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260802193000 extends AbstractMigration {
 public function getDescription():string{return 'Esquema inicial multi-tenant do Projeto Social';}
 public function up(Schema $schema):void{
  $this->addSql("CREATE TABLE projeto_social (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(140) NOT NULL, slug VARCHAR(80) NOT NULL, email VARCHAR(180) DEFAULT NULL, telefone VARCHAR(30) DEFAULT NULL, ativo TINYINT NOT NULL, criado_em DATETIME NOT NULL, UNIQUE INDEX UNIQ_PROJETO_SLUG (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, email VARCHAR(180) NOT NULL, nome VARCHAR(120) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, ativo TINYINT NOT NULL, UNIQUE INDEX UNIQ_USER_EMAIL (email), INDEX IDX_USER_PROJETO (projeto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE responsavel (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, usuario_id INT DEFAULT NULL, nome VARCHAR(120) NOT NULL, cpf VARCHAR(20) DEFAULT NULL, telefone VARCHAR(30) NOT NULL, email VARCHAR(180) DEFAULT NULL, recebe_notificacoes TINYINT NOT NULL, INDEX IDX_RESP_PROJETO (projeto_id), INDEX IDX_RESP_USER (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE professor (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, usuario_id INT DEFAULT NULL, nome VARCHAR(120) NOT NULL, email VARCHAR(180) DEFAULT NULL, especialidades LONGTEXT DEFAULT NULL, formacao LONGTEXT DEFAULT NULL, ativo TINYINT NOT NULL, INDEX IDX_PROF_PROJETO (projeto_id), INDEX IDX_PROF_USER (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE turma (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, professor_id INT DEFAULT NULL, nome VARCHAR(120) NOT NULL, ano_letivo INT NOT NULL, limite_alunos INT NOT NULL, horario VARCHAR(120) DEFAULT NULL, ativa TINYINT NOT NULL, INDEX IDX_TURMA_PROJETO (projeto_id), INDEX IDX_TURMA_PROF (professor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE aluno (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, responsavel_id INT DEFAULT NULL, turma_id INT DEFAULT NULL, usuario_id INT DEFAULT NULL, nome VARCHAR(120) NOT NULL, data_nascimento DATE NOT NULL, cpf VARCHAR(20) DEFAULT NULL, telefone VARCHAR(30) DEFAULT NULL, status VARCHAR(20) NOT NULL, qualificacao VARCHAR(20) NOT NULL, INDEX IDX_ALUNO_PROJETO (projeto_id), INDEX IDX_ALUNO_RESP (responsavel_id), INDEX IDX_ALUNO_TURMA (turma_id), INDEX IDX_ALUNO_USER (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE aula (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, turma_id INT DEFAULT NULL, titulo VARCHAR(160) NOT NULL, data_hora DATETIME NOT NULL, planejamento LONGTEXT DEFAULT NULL, execucao LONGTEXT DEFAULT NULL, materiais LONGTEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, INDEX IDX_AULA_PROJETO (projeto_id), INDEX IDX_AULA_TURMA (turma_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE frequencia (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, aula_id INT NOT NULL, aluno_id INT NOT NULL, situacao VARCHAR(20) NOT NULL, justificativa LONGTEXT DEFAULT NULL, notificacao_enviada TINYINT NOT NULL, UNIQUE INDEX UNIQ_FREQUENCIA (aula_id, aluno_id), INDEX IDX_FREQ_PROJETO (projeto_id), INDEX IDX_FREQ_ALUNO (aluno_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE fila_espera (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, turma_desejada_id INT DEFAULT NULL, nome VARCHAR(120) NOT NULL, data_nascimento DATE NOT NULL, telefone VARCHAR(30) NOT NULL, pontuacao INT NOT NULL, status VARCHAR(20) NOT NULL, inscrito_em DATETIME NOT NULL, INDEX IDX_FILA_PROJETO (projeto_id), INDEX IDX_FILA_TURMA (turma_desejada_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE prioridade_fila (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, nome VARCHAR(120) NOT NULL, pontos INT NOT NULL, ativa TINYINT NOT NULL, INDEX IDX_PRIOR_PROJETO (projeto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE movimentacao_financeira (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, tipo VARCHAR(20) NOT NULL, descricao VARCHAR(160) NOT NULL, valor NUMERIC(12,2) NOT NULL, data DATE NOT NULL, categoria VARCHAR(80) DEFAULT NULL, comprovante VARCHAR(255) DEFAULT NULL, publica TINYINT NOT NULL, INDEX IDX_FIN_PROJETO (projeto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  $this->addSql("CREATE TABLE configuracao_sistema (id INT AUTO_INCREMENT NOT NULL, projeto_id INT NOT NULL, chave VARCHAR(120) NOT NULL, valor LONGTEXT DEFAULT NULL, grupo VARCHAR(40) NOT NULL, tipo VARCHAR(20) NOT NULL, UNIQUE INDEX UNIQ_CONFIG_PROJETO_CHAVE (projeto_id,chave), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4");
  foreach(['`user`'=>'IDX_USER_PROJETO','responsavel'=>'IDX_RESP_PROJETO','professor'=>'IDX_PROF_PROJETO','turma'=>'IDX_TURMA_PROJETO','aluno'=>'IDX_ALUNO_PROJETO','aula'=>'IDX_AULA_PROJETO','frequencia'=>'IDX_FREQ_PROJETO','fila_espera'=>'IDX_FILA_PROJETO','prioridade_fila'=>'IDX_PRIOR_PROJETO','movimentacao_financeira'=>'IDX_FIN_PROJETO','configuracao_sistema'=>'UNIQ_CONFIG_PROJETO_CHAVE'] as $table=>$name)$this->addSql("ALTER TABLE $table ADD CONSTRAINT FK_".str_replace('`','',$name)." FOREIGN KEY (projeto_id) REFERENCES projeto_social (id) ON DELETE CASCADE");
  $this->addSql('ALTER TABLE responsavel ADD CONSTRAINT FK_RESP_USER FOREIGN KEY (usuario_id) REFERENCES `user` (id)');$this->addSql('ALTER TABLE professor ADD CONSTRAINT FK_PROF_USER FOREIGN KEY (usuario_id) REFERENCES `user` (id)');$this->addSql('ALTER TABLE turma ADD CONSTRAINT FK_TURMA_PROF FOREIGN KEY (professor_id) REFERENCES professor (id)');$this->addSql('ALTER TABLE aluno ADD CONSTRAINT FK_ALUNO_RESP FOREIGN KEY (responsavel_id) REFERENCES responsavel (id)');$this->addSql('ALTER TABLE aluno ADD CONSTRAINT FK_ALUNO_TURMA FOREIGN KEY (turma_id) REFERENCES turma (id)');$this->addSql('ALTER TABLE aluno ADD CONSTRAINT FK_ALUNO_USER FOREIGN KEY (usuario_id) REFERENCES `user` (id)');$this->addSql('ALTER TABLE aula ADD CONSTRAINT FK_AULA_TURMA FOREIGN KEY (turma_id) REFERENCES turma (id)');$this->addSql('ALTER TABLE frequencia ADD CONSTRAINT FK_FREQ_AULA FOREIGN KEY (aula_id) REFERENCES aula (id)');$this->addSql('ALTER TABLE frequencia ADD CONSTRAINT FK_FREQ_ALUNO FOREIGN KEY (aluno_id) REFERENCES aluno (id)');$this->addSql('ALTER TABLE fila_espera ADD CONSTRAINT FK_FILA_TURMA FOREIGN KEY (turma_desejada_id) REFERENCES turma (id)');
 }
 public function down(Schema $schema):void{foreach(['frequencia','fila_espera','aluno','aula','turma','professor','responsavel','prioridade_fila','movimentacao_financeira','configuracao_sistema','`user`','projeto_social'] as $table)$this->addSql("DROP TABLE $table");}
}
