<?php
namespace App\Controller;
use App\Entity\User;
use App\Service\BillingManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\{File\UploadedFile,Request,Response};
use Symfony\Component\Routing\Attribute\Route;
final class IdentityVisualController extends AbstractController {
 #[Route('/configuracoes/identidade-visual',name:'app_identity_visual',methods:['GET','POST'])]
 public function index(Request $request,EntityManagerInterface $em,BillingManager $billing):Response{$this->denyAccessUnlessGranted('ROLE_MASTER');$user=$this->getUser();if(!$user instanceof User||!$user->getProjeto())throw $this->createAccessDeniedException();$project=$user->getProjeto();if(!$billing->hasFeature($project,'identidade_visual'))throw $this->createAccessDeniedException('A identidade visual personalizada não está incluída no plano atual.');$errors=[];if($request->isMethod('POST')){if(!$this->isCsrfTokenValid('identity-visual',(string)$request->request->get('_token')))throw $this->createAccessDeniedException();foreach(['corPrimaria','corSecundaria','corSidebar','corTextoBotao'] as $field){$color=strtolower(trim((string)$request->request->get($field)));if(!preg_match('/^#[0-9a-f]{6}$/',$color))$errors[]='Informe cores válidas no formato hexadecimal.';else$project->$field=$color;}$project->slogan=mb_substr(trim((string)$request->request->get('slogan')),0,160)?:null;if($request->request->has('remove_logo'))$project->logoPath=null;if($request->request->has('remove_banner'))$project->bannerPath=null;$logo=$request->files->get('logo');$banner=$request->files->get('banner');if($logo instanceof UploadedFile){$path=$this->upload($logo,$project->id,'logo',1024*1024,$errors);if($path)$project->logoPath=$path;}if($banner instanceof UploadedFile){$path=$this->upload($banner,$project->id,'banner',2*1024*1024,$errors);if($path)$project->bannerPath=$path;}if(!$errors){$em->flush();$this->addFlash('success','Identidade visual atualizada.');return $this->redirectToRoute('app_identity_visual');}}return $this->render('settings/identity.html.twig',['project'=>$project,'errors'=>$errors]);}
 private function upload(UploadedFile $file,int $projectId,string $kind,int $limit,array &$errors):?string{if($file->getSize()>$limit){$errors[]='A imagem de '.$kind.' excede o tamanho permitido.';return null;}$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$mime=$file->getMimeType();if(!isset($allowed[$mime])){$errors[]='Use imagens JPG, PNG ou WebP.';return null;}$directory=$this->getParameter('kernel.project_dir').'/public/uploads/projects/'.$projectId;$filename=$kind.'-'.bin2hex(random_bytes(8)).'.'.$allowed[$mime];try{if(!is_dir($directory)&&!mkdir($directory,0775,true)&&!is_dir($directory))throw new \RuntimeException();$file->move($directory,$filename);}catch(\Throwable){$errors[]='Não foi possível salvar a imagem.';return null;}return '/uploads/projects/'.$projectId.'/'.$filename;}
}
