<?php
namespace App\Controller;
use App\Entity\{Aluno,Assinatura,Aula,ConfiguracaoSistema,FilaEspera,Frequencia,Modalidade,MovimentacaoFinanceira,NotificacaoLog,PagamentoSaas,Plano,PrioridadeFila,Professor,ProjetoSocial,Responsavel,Turma,User};
use App\Service\BillingManager;
use App\Service\FeatureCatalog;
use App\Service\DocumentoValidator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\{Request,Response};
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\AsciiSlugger;
#[Route('/superadmin')]
final class SuperAdminController extends AbstractController {
 #[Route('',name:'app_superadmin_index',methods:['GET'])]
 public function index(EntityManagerInterface $em,BillingManager $billing):Response{$projects=$em->getRepository(ProjetoSocial::class)->findBy([],['criadoEm'=>'DESC']);$stats=[];foreach($projects as $p)$stats[$p->id]=['users'=>$em->getRepository(User::class)->count(['projeto'=>$p]),'students'=>$em->getRepository(Aluno::class)->count(['projeto'=>$p]),'subscription'=>$billing->subscription($p)];return $this->render('superadmin/index.html.twig',['projects'=>$projects,'stats'=>$stats,'totalUsers'=>$em->getRepository(User::class)->count([])]);}
 #[Route('/projetos/novo',name:'app_superadmin_project_new',methods:['GET','POST'])]
 public function newProject(Request $r,EntityManagerInterface $em,UserPasswordHasherInterface $hasher,BillingManager $billing,DocumentoValidator $documents):Response{$errors=[];$plans=$em->getRepository(Plano::class)->findBy(['ativo'=>true],['valorMensal'=>'ASC']);if($r->isMethod('POST')){if(!$this->isCsrfTokenValid('new-project',(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$name=trim((string)$r->request->get('nome'));$cnpj=$documents->normalize((string)$r->request->get('cnpj'));$owner=trim((string)$r->request->get('owner'));$email=mb_strtolower(trim((string)$r->request->get('email')));$password=(string)$r->request->get('password');$plan=$em->getRepository(Plano::class)->find((int)$r->request->get('plano'));if(mb_strlen($name)<3)$errors[]='Informe o nome da ONG.';if(!$documents->cnpj($cnpj)||$em->getRepository(ProjetoSocial::class)->findOneBy(['cnpj'=>$cnpj]))$errors[]='CNPJ inválido ou já cadastrado.';if(mb_strlen($owner)<3)$errors[]='Informe o responsável.';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$em->getRepository(User::class)->findOneBy(['email'=>$email]))$errors[]='E-mail inválido ou já cadastrado.';if(strlen($password)<8)$errors[]='A senha deve ter 8 caracteres.';if(!$plan)$errors[]='Selecione um plano.';if(!$errors){$p=new ProjetoSocial();$p->nome=$name;$p->cnpj=$cnpj;$p->slug=(new AsciiSlugger())->slug($name)->lower().'-'.substr(bin2hex(random_bytes(3)),0,6);$p->email=$email;$u=(new User())->setNome($owner)->setEmail($email)->setProjeto($p)->setRoles(['ROLE_MASTER']);$u->setPassword($hasher->hashPassword($u,$password));$em->persist($p);$em->persist($u);$billing->createTrial($p,$plan);$em->flush();$this->addFlash('success','ONG, assinatura e usuário Master criados.');return $this->redirectToRoute('app_superadmin_index');}}return $this->render('superadmin/new_project.html.twig',['plans'=>$plans,'errors'=>$errors]);}
 #[Route('/projeto/{id}',name:'app_superadmin_project',requirements:['id'=>'\d+'],methods:['GET','POST'])]
 public function project(ProjetoSocial $project,Request $request,EntityManagerInterface $em,BillingManager $billing,DocumentoValidator $documents):Response{if($request->isMethod('POST')){if(!$this->isCsrfTokenValid('project-'.$project->id,(string)$request->request->get('_token')))throw $this->createAccessDeniedException();$name=trim((string)$request->request->get('nome'));$cnpj=$documents->normalize((string)$request->request->get('cnpj'));$duplicate=$em->getRepository(ProjetoSocial::class)->findOneBy(['cnpj'=>$cnpj]);if(mb_strlen($name)<3)$this->addFlash('error','Informe um nome válido.');elseif(!$documents->cnpj($cnpj)||($duplicate&&$duplicate!==$project))$this->addFlash('error','CNPJ inválido ou já cadastrado.');else{$project->nome=$name;$project->cnpj=$cnpj;$project->email=trim((string)$request->request->get('email'))?:null;$project->telefone=trim((string)$request->request->get('telefone'))?:null;$project->ativo=$request->request->has('ativo');$em->flush();$this->addFlash('success','Projeto atualizado.');return $this->redirectToRoute('app_superadmin_index');}}return $this->render('superadmin/project.html.twig',['project'=>$project,'users'=>$em->getRepository(User::class)->findBy(['projeto'=>$project],['nome'=>'ASC']),'subscription'=>$billing->subscription($project),...$this->projectDashboard($project,$em)]);}
 #[Route('/projeto/{id}/detalhes',name:'app_superadmin_project_details',requirements:['id'=>'\d+'],methods:['GET'])]
 public function projectDetails(ProjetoSocial $project,EntityManagerInterface $em,BillingManager $billing):Response{return $this->render('superadmin/project_details.html.twig',['project'=>$project,'subscription'=>$billing->subscription($project),...$this->projectDashboard($project,$em)]);}
 #[Route('/projeto/{id}/status',name:'app_superadmin_project_status',requirements:['id'=>'\d+'],methods:['POST'])]
 public function status(ProjetoSocial $project,Request $request,EntityManagerInterface $em):Response{if(!$this->isCsrfTokenValid('status-'.$project->id,(string)$request->request->get('_token')))throw $this->createAccessDeniedException();$project->ativo=!$project->ativo;$em->flush();$this->addFlash('success',$project->ativo?'Projeto ativado.':'Projeto suspenso.');return $this->redirectToRoute('app_superadmin_index');}
 #[Route('/planos',name:'app_superadmin_plans',methods:['GET','POST'])]
 public function plans(Request $r,EntityManagerInterface $em):Response{if($r->isMethod('POST')){if(!$this->isCsrfTokenValid('plan-form',(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$plan=new Plano();$this->fillPlan($plan,$r);$em->persist($plan);$em->flush();$this->addFlash('success','Plano criado.');return $this->redirectToRoute('app_superadmin_plans');}return $this->render('superadmin/plans.html.twig',['plans'=>$em->getRepository(Plano::class)->findBy([],['valorMensal'=>'ASC']),'features'=>FeatureCatalog::FEATURES,'channels'=>FeatureCatalog::CHANNELS]);}
 #[Route('/planos/{id}',name:'app_superadmin_plan_edit',requirements:['id'=>'\d+'],methods:['GET','POST'])]
 public function planEdit(Plano $plan,Request $r,EntityManagerInterface $em):Response{if($r->isMethod('POST')){if(!$this->isCsrfTokenValid('plan-'.$plan->id,(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$this->fillPlan($plan,$r);$em->flush();$this->addFlash('success','Plano atualizado.');return $this->redirectToRoute('app_superadmin_plans');}return $this->render('superadmin/plan_form.html.twig',['plan'=>$plan,'features'=>FeatureCatalog::FEATURES,'channels'=>FeatureCatalog::CHANNELS]);}
 #[Route('/assinaturas',name:'app_superadmin_subscriptions',methods:['GET'])]
 public function subscriptions(EntityManagerInterface $em):Response{return $this->render('superadmin/subscriptions.html.twig',['subscriptions'=>$em->getRepository(Assinatura::class)->findBy([],['vencimento'=>'ASC'])]);}
 #[Route('/assinaturas/{id}',name:'app_superadmin_subscription_edit',requirements:['id'=>'\d+'],methods:['GET','POST'])]
 public function subscriptionEdit(Assinatura $subscription,Request $r,EntityManagerInterface $em):Response{$plans=$em->getRepository(Plano::class)->findBy(['ativo'=>true],['nome'=>'ASC']);if($r->isMethod('POST')){if(!$this->isCsrfTokenValid('subscription-'.$subscription->id,(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$plan=$em->getRepository(Plano::class)->find((int)$r->request->get('plano'));if($plan)$subscription->plano=$plan;$subscription->status=(string)$r->request->get('status');$subscription->vencimento=new \DateTimeImmutable((string)$r->request->get('vencimento'));$subscription->diasCarencia=max(0,(int)$r->request->get('diasCarencia'));$custom=trim((string)$r->request->get('limiteUsuarios'));$subscription->limiteUsuariosPersonalizado=$custom===''?null:max(1,(int)$custom);$em->flush();$this->addFlash('success','Assinatura atualizada.');return $this->redirectToRoute('app_superadmin_subscriptions');}return $this->render('superadmin/subscription_form.html.twig',['subscription'=>$subscription,'plans'=>$plans]);}
 #[Route('/pagamentos',name:'app_superadmin_payments',methods:['GET','POST'])]
 public function payments(Request $r,EntityManagerInterface $em):Response{$subscriptions=$em->getRepository(Assinatura::class)->findAll();if($r->isMethod('POST')){if(!$this->isCsrfTokenValid('payment-form',(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$subscription=$em->getRepository(Assinatura::class)->find((int)$r->request->get('assinatura'));if(!$subscription)throw $this->createNotFoundException();$payment=new PagamentoSaas();$payment->assinatura=$subscription;$payment->valor=(string)$r->request->get('valor');$payment->vencimento=new \DateTimeImmutable((string)$r->request->get('vencimento'));$payment->metodo=trim((string)$r->request->get('metodo'))?:null;$payment->referencia=trim((string)$r->request->get('referencia'))?:null;$em->persist($payment);$em->flush();$this->addFlash('success','Cobrança registrada.');return $this->redirectToRoute('app_superadmin_payments');}return $this->render('superadmin/payments.html.twig',['subscriptions'=>$subscriptions,'payments'=>$em->getRepository(PagamentoSaas::class)->findBy([],['criadoEm'=>'DESC'])]);}
 #[Route('/pagamentos/{id}/pago',name:'app_superadmin_payment_paid',requirements:['id'=>'\d+'],methods:['POST'])]
 public function paid(PagamentoSaas $payment,Request $r,EntityManagerInterface $em,BillingManager $billing):Response{if(!$this->isCsrfTokenValid('paid-'.$payment->id,(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$billing->markPaid($payment);$em->flush();$this->addFlash('success','Pagamento confirmado e acesso renovado.');return $this->redirectToRoute('app_superadmin_payments');}
 private function projectDashboard(ProjetoSocial $project,EntityManagerInterface $em):array{$count=fn(string $entity,array $criteria=[])=>$em->getRepository($entity)->count(['projeto'=>$project,...$criteria]);$group=function(string $entity,string $property)use($em,$project):array{$result=[];foreach($em->getRepository($entity)->findBy(['projeto'=>$project]) as $item){$key=(string)$item->$property;$result[$key]=($result[$key]??0)+1;}arsort($result);return $result;};$finance=['receita'=>0.0,'despesa'=>0.0];foreach($em->getRepository(MovimentacaoFinanceira::class)->findBy(['projeto'=>$project]) as $item)$finance[$item->tipo]=($finance[$item->tipo]??0)+(float)$item->valor;return ['stats'=>['users'=>$count(User::class),'activeUsers'=>$count(User::class,['ativo'=>true]),'students'=>$count(Aluno::class),'activeStudents'=>$count(Aluno::class,['status'=>'ativo']),'teachers'=>$count(Professor::class),'responsibles'=>$count(Responsavel::class),'classes'=>$count(Turma::class),'activeClasses'=>$count(Turma::class,['ativa'=>true]),'modalities'=>$count(Modalidade::class),'lessons'=>$count(Aula::class),'notifications'=>$count(NotificacaoLog::class),'waitlist'=>$count(FilaEspera::class),'financeEntries'=>$count(MovimentacaoFinanceira::class),'attendance'=>$count(Frequencia::class),'priorities'=>$count(PrioridadeFila::class),'settings'=>$count(ConfiguracaoSistema::class),'publicEntries'=>$count(MovimentacaoFinanceira::class,['publica'=>true])],'notificationTypes'=>$group(NotificacaoLog::class,'canal'),'notificationStatus'=>$group(NotificacaoLog::class,'status'),'notifications'=>$em->getRepository(NotificacaoLog::class)->findBy(['projeto'=>$project],['criadoEm'=>'DESC'],8),'attendance'=>$group(Frequencia::class,'situacao'),'waitlistStatus'=>$group(FilaEspera::class,'status'),'finance'=>$finance];} private function fillPlan(Plano $plan,Request $r):void{$plan->nome=trim((string)$r->request->get('nome'));$plan->valorMensal=(string)$r->request->get('valorMensal');$plan->limiteUsuarios=max(1,(int)$r->request->get('limiteUsuarios'));$plan->limiteTurmas=max(1,(int)$r->request->get('limiteTurmas'));$students=trim((string)$r->request->get('limiteAlunos'));$plan->limiteAlunos=$students===''?null:max(1,(int)$students);$notifications=trim((string)$r->request->get('limiteNotificacoesMes'));$plan->limiteNotificacoesMes=$notifications===''?null:max(0,(int)$notifications);$plan->limiteArmazenamentoMb=max(100,(int)$r->request->get('limiteArmazenamentoMb'));$plan->diasTeste=max(0,(int)$r->request->get('diasTeste'));$plan->recursos=array_values(array_intersect($r->request->all('recursos'),array_keys(FeatureCatalog::FEATURES)));$plan->canaisNotificacao=array_values(array_intersect($r->request->all('canais'),array_keys(FeatureCatalog::CHANNELS)));$plan->ativo=$r->request->has('ativo');$plan->publico=$r->request->has('publico');}
}
